build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Smart Gate v1"
  org.opencontainers.image.description: "Smart gate automations, automatic gate opening with plate recognition"
  org.opencontainers.image.source: "https://github.com/andreaemmanuele/haos_smartgate"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
